apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  url: ssh://git@github.com/enes789/flux_demo
  ref:
    branch: main
  secretRef:
    name: podinfo-auth 